### ISSUE TITLE
10 - Release!

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/local-placeholder-images#10]
Alors pour pas te cause trop de trouble au cas ou tu avais deja un index.js, j'ai cree index.example.js et  l'ai declare dans le `package.json` dans la cle `main`

J'ai aussi cree les dossiers `lib` et `bin`

Tu verra souvent cette structure ou qqc de similaire. C'est une question d'organisation plus que autre chose. 

Si tu ouvres `index.example.js` tu remarquera qu'il ya a peu de code.... le code se trouve dans /lib et est divise en deux mini librairies, au cas ou on veut juste la partie generation d'images si on a deja un serveur (ex: une app express.js). 

Alors si tu regardes ensuite dans `/lib/canvas.js` et `/lib/server.js` tu retrouvera le code des exemples, mais avec quelques variations pour les exportations.

J'ai aussi cree un ficher dans '/bin/index.js' et j'ai ajoutte se ficher dans la cle `bin` de notre `package.json` en lui donnant le nom `serve-placeholders`

J'indique ainsi a npm que si qq'un fais 

'npm install local-placeholder-images -g` 

(-g pour global)

npm devra creer une commande `serve-placeholders` en utilisant se ficher. 

Dans le cas de ton proper package, tu peut l'installer globalement sans specifier le nom, si tu est dans le repertoire de ton package. 

`npm install -g`

qui devrais te donner la possibilite de maintenant faire simplement 

`serve-placeholders --port 8080`

pour demarrer le service sur le port 8080.

Questions?

**Comment by pom2ter** [comment]
pas assez de pratique pour avoir des questions :o

**Comment by AKRFranko** [comment]
Ok, alors je level up la difficulte...
