### ISSUE TITLE
Dojo Practice #1

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/local-placeholder-images#11]
En ce moment, on doit passer les parametres ainsi:

`http://localhost:8080?width=300&height=400&text=FFFFFF&background=000000`

J'aimerai pouvoir le faire ainsi:

`http://localhost:8080/300/400/FFFFFF/000000`

Au lieu de re-inventer la roue, tu ferais mieux d'utiliser le module http://expressjs.com/

Tu devra alors modifier `lib/server.js` pour supporter cette nouvelle fonctionalite. 

Avec un example d'un serveur express de base:

```
  var express = require('express');
  var app = express();

  app.get('/', function(req, res){
     res.send('hello world');
  });

  app.listen(3000);
```

Et une comprehension des "named route parameters" http://expressjs.com/4x/api.html#req.params 
tu devrais t'en sortir sans probleme.

**Comment by pom2ter** [comment]
jai une version boboche qui marche si il y a 4 parametres

**Comment by AKRFranko** [comment]
Je check sa dans pas long.
