### ISSUE TITLE
04 - node-canvas dependency

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/local-placeholder-images#4]
Comment on declare que notre module sera dependant d'un autre module? En l'ajouttant dans la cle "dependencies" de notre package.json. 

Mais faire a la main c'est chiant. Alors tu le fais en meme temps que tu installes le package. 

Normalement, on installe un package ainsi:

`npm install nameofpackage`

Mais si tu veut automatiquement le mettre dans ton package.json comme dependance, tu ajouttes `--save-dev` ou tout simpement `-D`

`npm install --save-dev nameofpackage`

tu peut  aussi oublier d'ecrire install au complet et simplement faire:

`npm i -D nameofpackage`

qui est la meme chose que:

`npm install --save-dev nameofpackage`

ou:

`npm install -D nameofpackage`

Alors pour ici tu fais:

`npm i -D canvas`

(si tu as des erreurs qui mentionnent node-gyp et python, tu peut essayer `export PYTHON=python2.7 && npm i -D canvas )

**Comment by pom2ter** [comment]
j'ai du installé d'autres dépendances pis faire tout fonctionner avec homebrew parce qu'il y avait des conflicts.

**Comment by AKRFranko** [comment]
Surement en relation avec cairo ou node-canvas. 

C'etais un peu voulu. Dans un futur proche, on utilisera https://github.com/filamentgroup/grunticon pour generer des spritesheet svg. 

Ceci fait partie des choses cool que te permet de faire grunt. Grunticon par-contre utilise aussi node-canvas. Alors en prevision de ne pas te faire rusher pour rien dans un plus gros projet, je t'ai reproduis le probleme de cette facon ;P
