### ISSUE TITLE
06 - Almost done. Code skills!

### ISSUE THREAD

**Issue by AKRFranko** [AKRFranko/local-placeholder-images#6]
Alors pour inclure les deux modules que tu as besoin, tu utilises la fonction 'require'

`
var http = require('http');
var Canvas = require('canvas');
`

Essentiellement, un serveur http c'est quelques lignes:

```
var port = 8080;  
var server = http.createServer(function (request, response) {
   response.writeHead( 200, { 'Content-Type': 'text/plain' } );
   response.end( 'Hullo Wurld!' )
}
server.listen( port );
```

Ce qui sera un peu plus complique a comprendre, mais facile a faire c'est que tu peut aussi envoyer un 'stream' de data au lieu d'un string. Parfait! Car node-canvas marche tres bien ainsi et cela eliminera le besoin de creer les images sur disque. 

Alors tu peut creer ton canvas ainsi:

```
var canvas = new Canvas( 512, 512 );
/* 
     Manipule ton canvas comme en html pour atteindre l'objectif.
     ex: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text 
 */
```

Ensuite, tu peut servir le stream directement par ton serveur http

```
// ... canvas manipulations, ensuite: 
var stream = canvas.createPNGStream();
response.writeHead(200, {"Content-Type": "image/png"});
stream.pipe(response);
```

Quand tu sera rendu ici, re-assigne moi ce ticket, et on vera les prochaines etapes du tuto.

**Comment by pom2ter** [comment]
on peut dire je suis rendu ici, mais sans avoir faire les manipulations du canvas

**Comment by AKRFranko** [comment]
Alright! Wunderbar! ...
